### ISSUE TITLE
Max number of classes 

### ISSUE THREAD

**Issue by elena-orlova** [SsnL/dataset-distillation#28]
Hello! 

Am I right that the maximum number of classes on that you tested the distillation  algorithm is 200 classes (CUB200)? Which GPU did you use? 
I’m trying to run the code for more than 10 classes, and my GPU out of memory even for 15 classes. But it’s Tesla V100, and I can’t reproduce results for CUB200. Or you parallelized the algorithm somehow?

**Comment by SsnL** [comment]
Hi! With large number of classes, you can try reducing #images_per_class and #GD_steps. For CUB200 experiment, we did 200 images (1 per class) repeatedly trained for 3 GD steps. Another option is to use gradient checkpointing: instead of saving the graph for all steps in forward, recompute (some of) them at backward time, i.e., a tradeoff between memory and time. That approach allowed us to use more GD steps, but eventually it turned out not necessary for the experiments in the paper.

Our experiments were done on V100 or Titan Xps.

**Comment by SsnL** [comment]
I'm closing this for now. Feel free to reopen/open a new issue if there are further questions!
